### ISSUE TITLE
[feat] : 엔티티를 생성한다

### ISSUE THREAD

**Issue by Ganghee-Lee-0522** [Basement02/PeepIt-Server#1]
### 📝 Description

- 엔티티 클래스를 생성한다
- JPA Repository를 생성한다

---

### 📝 Todo

- [x] 모든 엔티티 생성
- [x] 모든 JPA Repo 생성
- [x] local db 생성
