### ISSUE TITLE
[feat] : submodule을 설정한다

### ISSUE THREAD

**Issue by Ganghee-Lee-0522** [Basement02/PeepIt-Server#2]
### 📝 Description

- submodule을 설정한다

---

### 📝 Todo

- [x] private submodule repo 생성
- [x] public repo에 위 private repo를 연결
- [x] yml 파일을 분리하고, 기본 yml 파일을 public에 push
